(() => {
  "use strict";

  module.exports = {
    message: {
      saveMessage: "User created successfully. Please check your email inbox for further instructions.",
      sms_max_entry: "Max SMS quota for the day exceeded. Please try again with different number",
      sms_max_entry_per_ip: "Max SMS quota for the IP address exceeded.",
      invalid_sms_token: "Invalid SMS token",
      saveMessageAdminUser: "User created successfully.",
      saveMessageAdminUserFailure: "OOPS! Something went wrong.",
      updateMessage: "User updated successfully",
      deleteMessage: "User deleted successfully",
      suspendMessage: "User suspended successfully",
      removeSuspension: "User suspension removed successfully",
      suspendMessageUnable:"User with superadmin role cannot be suspended",
      passwordUpdateMessage: "Password changed successfully",
      securityAnswerMessage: "Security answer updated successfully",
      notFound: "User information not found",
      emailConfirmationLink: "Email confirmation link sent successfully",
      fieldRequired: "Username is required",
      alreadyExists: "User with same email or validated mobile number already exists",
      alreadyExistsUsername: "User with same email already exists",
      alreadyExistsSignupMobileNumber: "User with same mobile number already exists",
      alreadyExistsMobileNumber: "Mobile number is already validated by other user",
      superAdminDeleteMessage: "Superadmin user cannot be deleted",
      blockStatusMessage: "User unblocked successfully",
      emailUpdateMessage: "User email updated successfully",
      passwordEqUsername : "Password must not contain the username",
      passwordSame: "Please use different password. i.e Please enter valid old password and new password must be at least 6 characters long",//containing a combination of lowercase, uppercase, numbers and special characters,
      passwordChangeConfirmationEmail : "An email has been sent to your email address that contains the link to change your password.Please check your email",
      weakPassword : "Password is very weak. Password should be at least 6 characters long",//Please try the combination of lowercase alphabets, uppercase alphabets, numbers, symbols and a minimum of 8 characters long password
      notAuthorizedForSecurityAnswerUpdate : "You are not authorized to change the password. Please enter the valid email address registered with XcelTrip",
      notAllowedToChangeSuperAdminPassword: "You are not allowed to change the password of superadmin",
      notAllowedToChangeOthersPassword: "You are not allowed to change the password of other user",
      notAllowedToChangePassword: "You are not allowed to change the password",
      passwordMatchOldPassword: "Please enter different password than the old one.",
      emailError: "OOPS!!! Error occurs while sending email...Please contact site administrator",
      invalidMessage: "Invalid credentials",
      accountNotConfirmed: "User email not confirmed. Please click on the link sent to you in the confirmation email to verify your account.",
      blockMessage: "You are currently blocked. Please check your email and click the link.",
      ipBlocked : "Your ip address has been blocked due to repeated entry of invalid login credentials",
      authProgress : "Authentication already in progress",
      suspensionMessage : "You are suspended currently. For further info, please contact the site administrator",
      accountAlreadyConfirmed: "Account already confirmed",
      sms_sent: 'Validity Token sent through the SMS successfully',
      sms_error: "Error while sending SMS...Please check your mobile number.",
      notFound_sms: "SMS token not found",
      mobile_number_validated: 'Mobile number already validated',
      mobile_number_not_exists: "Mobile number doesn't appear to be associated to the user account",
      mobile_validation_success: "Mobile number validated successfully.",
      mobile_remove_success: "Mobile number removed successfully",
      user_logout: "User logged out of the system successfully",
      oldPasswordMismatch: "The old password you entered is invalid",
      passwordNotStrong: "Password must be at least 6 characters long ",//and must contain a combination of lowercase, uppercase, numbers and special characters
      captchEnable: "Captcha is enabled",
      bankAccountSavedSuccess:"Bank Account Saved",
      invalidEmail:"Please input valid email address",
      forgotEmailSendingFailure:"System unable to send the forgot password link",
      verify_mobile_number: "Please verify mobile number first to enable mobile two factor authentication",
      bankAccountDocumentDeleteSuccess: "Document deleted successfully",
      passwordNotSet: "Your user account has not been set password.",
      invalidEmailUpdateToken: "Email Update token is invalid. Either the time validity is expired or it might have been already used",
      invalidEmailVerificationToken: "Invalid verification token for the new email to be updated. It might have been already used or token is invalid.",
      userVerificationFailed: "Couldn't verify the previous email address specified by the user",
      emailUpdateSuccess: "Email updated successfully",
      notFoundTokenInfo: "Data not available",
      emailConfirmationTokenSent: "Email confirmation token sent successfully",
      emailUpdateVerificationTokenSent: "Verification link sent successfully",
        invalidUserId: "User Id is invalid. Please provide valid user id.",
      validationErrMessage:{
        first_name : "First name is required",
        last_name : "Last name is required",
        email : "Email is required",
        emailValid : "Invalid Email",
        user_role: "User role is required",
        gender: "Gender of the person is required",
        agree_terms_condition : "Please accept privacy Terms and Conditions",
        agree_terms_condition_valid: "Please enter valid boolean value",
        security_question: "security question is mandatory",
        security_answer: "security answer is mandatory",
        password : "Password is required",
        password_old: "Please enter old password",
        password_valid_length: "Password must be at least 6 characters long",
        username: "username is required",
        mobile_number: "Please enter valid mobile number",
        country_code: "Please enter country code",
        country_abbr:"Please provide Country abbreviation code",
        account_holder_name: "Please enter account holder's name",
        bank_name:"Bank Name is Required",
        swift_code:"Swift Code is Required",
        bank_branch_address:"Bank Branch Address is Required",
        routing_number_valid: "Please enter valid routing number",
        bank_account_type :"Please Select Bank Account Type",
        bank_account_number: "Please enter bank account number",
        billing_address_country: "Please enter country name for billing address",
        billing_address_city: "Please enter city name for billing address",
        billing_address_zip_postal_code: "Please enter zip/postal name for billing address",
        billing_address_state_region_province: "Please enter state/region/province name for billing address",
        billing_address_address_line_1: "Please enter Address Line 1 for billing address",
        previous_email: "Previous email address is required",
        previous_email_invalid: "Previous email address is invalid",
        new_email: "New email address is required",
        new_email_invalid: "New email address is invalid",
        email_verification_code: "Email Verification code is required"
      }
    },
    config: {
      documentFilePath: '/private-uploads/user-profiles/',
      uploadPrefix: 'user-profile',
      commonPasswordFilePath: '/lib/static-data/10k_most_common.txt',
      mobile_token_length: 6,
      token_length: 8,
      sms_message: 'Your XcelTrip verification code is',
      sms_sender: '+14439988664',
      token_expiry_date_in_mins: 25,
      verification_link: "email-update/verification/",
      token_expiry_date_in_hours: "720",
        max_sms_quota_per_ip: 10,
        max_sms_quota_per_day: 6
    },
    notifications: {
      welcome_message: "Welcome to the XcelTrip Travel Application. Best Travel Packages that no one can match.",
      email_confirmation_prompt_message: "To enjoy the best experiences, Please confirm your email by clicking the link sent to you.",
      profile_info_message: "Your profile information has been updated.",
      email_update_message: "Your username and email is updated successfully. Please use new username to get access to the dashboard."
    },
    push_notification: {
      title: {
        welcome_message: "Welcome to XcelTrip",
        email_update_message: "Username and Email update Notification",
        profile_information_updated: "Profile information updated"
      }
    }
  };

})();
