export const VERIFY_MULTI_FACTOR_AUTH_REQUEST = "XcelTrip/AdminProfile/MultiFactorAuth/VERIFY_MULTI_FACTOR_AUTH_REQUEST";
export const VERIFY_MULTI_FACTOR_AUTH_SUCCESS = "XcelTrip/AdminProfile/MultiFactorAuth/VERIFY_MULTI_FACTOR_AUTH_SUCCESS";
export const VERIFY_MULTI_FACTOR_AUTH_FAILURE = "XcelTrip/AdminProfile/MultiFactorAuth/VERIFY_MULTI_FACTOR_AUTH_FAILURE";

export const GET_MULTI_FACTOR_AUTH_REQUEST = "XcelTrip/AdminProfile/MultiFactorAuth/GET_MULTI_FACTOR_AUTH_REQUEST";
export const GET_MULTI_FACTOR_AUTH_SUCCESS = "XcelTrip/AdminProfile/MultiFactorAuth/GET_MULTI_FACTOR_AUTH_SUCCESS";
export const GET_MULTI_FACTOR_AUTH_FAILURE = "XcelTrip/AdminProfile/MultiFactorAuth/GET_MULTI_FACTOR_AUTH_FAILURE";

export const DISABLE_MULTI_FACTOR_AUTH_REQUEST = "XcelTrip/AdminProfile/MultiFactorAuth/DISABLE_MULTI_FACTOR_AUTH_REQUEST";
export const DISABLE_MULTI_FACTOR_AUTH_SUCCESS = "XcelTrip/AdminProfile/MultiFactorAuth/DISABLE_MULTI_FACTOR_AUTH_SUCCESS";
export const DISABLE_MULTI_FACTOR_AUTH_FAILURE = "XcelTrip/AdminProfile/MultiFactorAuth/DISABLE_MULTI_FACTOR_AUTH_FAILURE";


export const GET_RECOVERY_CODES_REQUEST = "XcelTrip/AdminProfile/MultiFactorAuth/GET_RECOVERY_CODES_REQUEST";
export const GET_RECOVERY_CODES_SUCCESS = "XcelTrip/AdminProfile/MultiFactorAuth/GET_RECOVERY_CODES_SUCCESS";
export const GET_RECOVERY_CODES_FAILURE = "XcelTrip/AdminProfile/MultiFactorAuth/GET_RECOVERY_CODES_FAILURE";


export const SEND_EMAIL_WITH_MFA_RECOVERY_REQUEST = "XcelTrip/AdminProfile/MultiFactorAuth/SEND_EMAIL_WITH_MFA_RECOVERY_REQUEST";
export const SEND_EMAIL_WITH_MFA_RECOVERY_SUCCESS = "XcelTrip/AdminProfile/MultiFactorAuth/SEND_EMAIL_WITH_MFA_RECOVERY_SUCCESS";
export const SEND_EMAIL_WITH_MFA_RECOVERY_FAILURE = "XcelTrip/AdminProfile/MultiFactorAuth/SEND_EMAIL_WITH_MFA_RECOVERY_FAILURE";

export const GENERATE_RECOVERY_CODE_REQUEST = "XcelTrip/AdminProfile/MultiFactorAuth/GENERATE_RECOVERY_CODE_REQUEST";
export const GENERATE_RECOVERY_CODE_SUCCESS = "XcelTrip/AdminProfile/MultiFactorAuth/GENERATE_RECOVERY_CODE_SUCCESS";
export const GENERATE_RECOVERY_CODE_FAILURE = "XcelTrip/AdminProfile/MultiFactorAuth/GENERATE_RECOVERY_CODE_FAILURE";

export const LOAD_BASIC_INFO_REQUEST = "XcelTrip/AdminProfile/BasicInfo/LOAD_BASIC_INFO_REQUEST";
export const LOAD_BASIC_INFO_SUCCESS = "XcelTrip/AdminProfile/BasicInfo/LOAD_BASIC_INFO_SUCCESS";
export const LOAD_BASIC_INFO_FAILURE = "XcelTrip/AdminProfile/BasicInfo/LOAD_BASIC_INFO_FAILURE";
